updated openhab init script

diff --git a/openhab/openhab b/openhab/openhab
--- a/openhab/openhab
+++ b/openhab/openhab
@@ -1,164 +1,179 @@
 #! /bin/sh
 ### BEGIN INIT INFO
 # Provides:          openhab
-# Required-Start:    $remote_fs $syslog
-# Required-Stop:     $remote_fs $syslog
+# Required-Start:    $all
+# Required-Stop:     $all
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: OpenHAB Daemon
+# Short-Description: openHAB server
+# Description:       Start / Stop openHAB server
 ### END INIT INFO
 
-# Author: Thomas Brettinger
+# Author: openHAB <openhab@openhab.org>
+#
 
-# Do NOT "set -e"
 
-# PATH should only include /usr/* if it runs after the mountnfs.sh script
 PATH=/sbin:/usr/sbin:/bin:/usr/bin
+OPENHAB_INST_DIR="/usr/share/openhab"
 
-DESC="Open Home Automation Bus Daemon"
+DESC="openHAB server"
 NAME=openhab
-DAEMON=/usr/bin/java
+JAVA="/usr/bin/java"
 PIDFILE=/var/run/$NAME.pid
 SCRIPTNAME=/etc/init.d/$NAME
-ECLIPSEHOME="/var/www/openhab";
-TELNETPORT=5555
-RUN_AS=klenov
+SETOWNER=yes
 
-# get path to equinox jar inside $eclipsehome folder
-cp=$(find $ECLIPSEHOME/server -name "org.eclipse.equinox.launcher_*.jar" | sort | tail -1);
+HTTP_PORT=8088
 
-DAEMON_ARGS="-Dosgi.clean=true -Declipse.ignoreApp=true -Dosgi.noShutdown=true -Djetty.port=8080 -Djetty.port.ssl=8443 -Djetty.home=$ECLIPSEHOME -Dlogback.configurationFile=$ECLIPSEHOME/configurations/logback.xml -Dfelix.fileinstall.dir=$ECLIPSEHOME/addons -Djava.library.path=$ECLIPSEHOME/lib -Djava.security.auth.login.config=$ECLIPSEHOME/etc/login.conf -Dorg.quartz.properties=$ECLIPSEHOME/etc/quartz.properties -Djava.awt.headless=true -jar $cp -console $TELNETPORT"
-
-# Exit if the package is not installed
-[ -x "$DAEMON" ] || exit 0
-
-# Read configuration variable file if it is present
-[ -r /etc/default/$NAME ] && . /etc/default/$NAME
-
-# Load the VERBOSE setting and other rcS variables
-. /lib/init/vars.sh
+# read defaults
+include="${OPENHAB_INST_DIR}/bin/openhab.in.sh"
+if [ -r "$include" ]; then
+    . "$include"
+else
+    echo "Error $include not found or not readable" >&2
+    exit 1
+fi
 
 # Define LSB log_* functions.
 # Depend on lsb-base (>= 3.2-14) to ensure that this file is present
 # and status_of_proc is working.
 . /lib/lsb/init-functions
 
-#
-# Function that starts the daemon/service
-#
-do_start()
-{
-    cd $ECLIPSEHOME
-    # Return
-    #   0 if daemon has been started
-    #   1 if daemon was already running
-    #   2 if daemon could not be started
-    start-stop-daemon --start --quiet --make-pidfile --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
-        || return 1
-    start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE --chuid $RUN_AS --chdir $ECLIPSEHOME --exec $DAEMON -- $DAEMON_ARGS \
-        || return 2
-    # Add code here, if necessary, that waits for the process to be ready
-    # to handle requests from services started subsequently which depend
-    # on this one.  As a last resort, sleep for some time.
-}
+LAUNCHER=`ls ${OPENHAB_DIR}/server/plugins/org.eclipse.equinox.launcher_*.jar`
 
-#
-# Function that stops the daemon/service
-#
-do_stop()
-{
-    # Return
-    #   0 if daemon has been stopped
-    #   1 if daemon was already stopped
-    #   2 if daemon could not be stopped
-    #   other if a failure occurred
-    start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
-    RETVAL="$?"
-    [ "$RETVAL" = 2 ] && return 2
-    # Wait for children to finish too if this is a daemon that forks
-    # and if the daemon is only ever run from this initscript.
-    # If the above conditions are not satisfied then add some other code
-    # that waits for the process to drop all resources that could be
-    # needed by services started subsequently.  A last resort is to
-    # sleep for some time.
-    start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
-    [ "$?" = 2 ] && return 2
-    # Many daemons don't delete their pidfiles when they exit.
-    rm -f $PIDFILE
-    return "$RETVAL"
-}
+# Exit if the package is not installed
+if [ ! -r "$LAUNCHER" ]; then
+    log_failure_msg "launcher jar is missing"
+    exit 5
+fi
 
-#
-# Function that sends a SIGHUP to the daemon/service
-#
-do_reload() {
-    #
-    # If the daemon can reload its configuration without
-    # restarting (for example, when it is sent a SIGHUP),
-    # then implement that here.
-    #
-    do_stop
-    sleep 1
-    do_start
-    return 0
-}
+if [ x"${OPENHAB_JAVA}" != x ]; then
+    JAVA="${OPENHAB_JAVA}"
+fi
+
+if [ ! -x "${JAVA}" ]; then
+    log_failure_msg "no java executable found at ${JAVA}"
+    exit 2
+fi
+
+if [ x"${USER_AND_GROUP}" != x ]; then
+
+    USER=`echo ${USER_AND_GROUP} | cut -d ":" -f 1`
+    GROUP=`echo ${USER_AND_GROUP} | cut -d ":" -f 2`
+
+    #Check whether the specified user exists
+    if ! getent passwd "${USER}" > /dev/null 2>&1; then
+        log_failure_msg "runtime user doesn't exists"
+        exit 2
+    fi
+
+    #Check whether the specified group exists
+    if ! getent group "${GROUP}" > /dev/null 2>&1; then
+        log_failure_msg "runtime group doesn't exists"
+        exit 2
+    fi
+
+    EXTRA_ARGS="-c "${USER_AND_GROUP}" --umask 002 --background --make-pidfile --chdir ${OPENHAB_DIR}"
+else
+    EXTRA_ARGS="--umask 002 --background --make-pidfile --chdir ${OPENHAB_DIR}"
+fi
+
+
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
+
+DEBUG_ARGS="-Xdebug \
+  -Xnoagent \
+  -Djava.compiler=NONE \
+  -Xrunjdwp:transport=dt_socket,address=8001,server=y,suspend=n \
+  -Dlogback.configurationFile=${OPENHAB_CONF_DIR}/logback_debug.xml"
+
+JAVA_ARGS_DEFAULT="-Dosgi.clean=true \
+ -Declipse.ignoreApp=true \
+ -Dosgi.noShutdown=true \
+ -Djetty.port=${HTTP_PORT} \
+ -Dopenhab.configfile="${OPENHAB_CONF_DIR}/configurations/openhab.cfg" \
+ -Dopenhab.configdir="${OPENHAB_CONF_DIR}/configurations" \
+ -Dopenhab.logdir="${OPENHAB_LOG_DIR}" \
+ -Dsmarthome.userdata="${OPENHAB_USER_DATA_DIR}"
+ -Djetty.home="${OPENHAB_DIR}" \
+ -Djetty.port.ssl=${HTTPS_PORT} \
+ -Djetty.config="${OPENHAB_CONF_DIR}/jetty" \
+ -Djetty.logs="${OPENHAB_LOG_DIR}" \
+ -Djetty.rundir="${OPENHAB_DIR}" \
+ -Dfelix.fileinstall.dir="${OPENHAB_DIR}/addons" \
+ -Dfelix.fileinstall.filter=.*\\.jar \
+ -Djava.library.path="${OPENHAB_DIR}/lib" \
+ -Djava.security.auth.login.config="${OPENHAB_CONF_DIR}/login.conf" \
+ -Dorg.quartz.properties="${OPENHAB_CONF_DIR}/quartz.properties" \
+ -Dequinox.ds.block_timeout=240000 \
+ -Dequinox.scr.waitTimeOnBlock=60000 \
+ -Dfelix.fileinstall.active.level=4 \
+ -Djava.awt.headless=true \
+ -jar ${LAUNCHER} \
+ -configuration ${OPENHAB_WORKSPACE_DIR} \
+ -data ${OPENHAB_WORKSPACE_DIR} \
+ -console ${TELNET_PORT}"
+
+if [ x"${JAVA_ARGS}" != x ]; then
+    JAVA_ARGS_DEFAULT="${JAVA_ARGS} ${JAVA_ARGS_DEFAULT}"
+fi
+
+if [ x"${OPENHAB_ARGS}" != x ]; then
+    JAVA_ARGS_DEFAULT="${JAVA_ARGS_DEFAULT} ${OPENHAB_ARGS}"
+fi
+
+if echo ${DEBUG} | grep -qi "^yes$"; then
+    JAVA_ARGS_DEFAULT="${DEBUG_ARGS} ${JAVA_ARGS_DEFAULT}"
+else
+    JAVA_ARGS_DEFAULT="-Dlogback.configurationFile=${OPENHAB_CONF_DIR}/logback.xml ${JAVA_ARGS_DEFAULT}"
+fi
 
 case "$1" in
   start)
-    [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
-    do_start
-    case "$?" in
-        0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-        2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-    esac
-    ;;
+        log_daemon_msg "Starting $DESC" "$NAME"
+    ${OPENHAB_INST_DIR}/bin/setpermissions.sh > /dev/null
+    if start-stop-daemon --start --quiet --pidfile $PIDFILE $EXTRA_ARGS \
+        --oknodo --exec $JAVA -- $JAVA_ARGS_DEFAULT
+    then
+            log_end_msg 0
+        else
+            log_end_msg 1
+        fi
+        ;;
   stop)
-    [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
-    do_stop
-    case "$?" in
-        0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-        2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-    esac
-    ;;
+        log_daemon_msg "Stopping $DESC" "$NAME"
+        if start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 \
+            --pidfile $PIDFILE --oknodo
+        then
+            rm -f $PIDFILE
+            log_end_msg 0
+        else
+            log_end_msg 1
+        fi
+        ;;
   status)
-       status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
-       ;;
-  #reload|force-reload)
-    #
-    # If do_reload() is not implemented then leave this commented out
-    # and leave 'force-reload' as an alias for 'restart'.
-    #
-    #log_daemon_msg "Reloading $DESC" "$NAME"
-    #do_reload
-    #log_end_msg $?
-    #;;
+        status_of_proc -p "$PIDFILE" "$JAVA" "$NAME" && exit 0 || exit $?
+        ;;
   restart|force-reload)
-    #
-    # If the "reload" option is implemented then remove the
-    # 'force-reload' alias
-    #
-    log_daemon_msg "Restarting $DESC" "$NAME"
-    do_stop
-    case "$?" in
-      0|1)
-        do_start
-        case "$?" in
-            0) log_end_msg 0 ;;
-            1) log_end_msg 1 ;; # Old process is still running
-            *) log_end_msg 1 ;; # Failed to start
-        esac
-        ;;
-      *)
-          # Failed to stop
+        log_daemon_msg "Restarting $DESC" "$NAME"
+        if start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 \
+            --pidfile $PIDFILE --oknodo
+        then
+            rm -f $PIDFILE
+            if start-stop-daemon --start --quiet --pidfile $PIDFILE $EXTRA_ARGS \
+                --oknodo --exec $JAVA -- $JAVA_ARGS_DEFAULT
+        then
+                log_end_msg 0
+            else
+                log_end_msg 1
+        fi
+    else
         log_end_msg 1
+    fi
         ;;
-    esac
-    ;;
   *)
-    #echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
-    echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
-    exit 3
-    ;;
+        echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+        exit 3
+        ;;
 esac
-
-:
